"""
This file contains all the default parameters used in the app
"""
import os
import typing

import pandas as pd
import nltk
import pathlib
import streamlit as st
from texthero import preprocessing
from datetime import datetime

STREAMLIT_STATIC_PATH = pathlib.Path(st.__path__[0]) / 'static'
DOWNLOAD_PATH = (STREAMLIT_STATIC_PATH / "downloads")

# download the corpus
nltk.download('words')

load_clean_visualise = {
    'FILE': 'Small File(s)',
    'MODE': 'CSV',
    'DATA_PATH': None,
    'DATA': pd.DataFrame(),
    'CSP': None,
    'CLEAN': False,
    'CLEAN_MODE': 'Simple',
    'SAVE': False,
    'OVERRIDE_FORMAT': None,
    'VERBOSE': False,
    'VERBOSITY': False,
    'CLEANED_DATA': pd.DataFrame(),
    'CLEANED_DATA_TOKENIZED': pd.DataFrame(),
    'ADVANCED_ANALYSIS': False,
    'SIMPLE_PIPELINE': [
        preprocessing.remove_html_tags,
        preprocessing.remove_diacritics,
        preprocessing.remove_whitespace,
        preprocessing.remove_urls,
        preprocessing.drop_no_content
    ],
    'PIPELINE': [
        preprocessing.fillna,
        preprocessing.lowercase,
        preprocessing.remove_punctuation,
        preprocessing.remove_html_tags,
        preprocessing.remove_diacritics,
        preprocessing.remove_whitespace,
        preprocessing.remove_urls,
        preprocessing.drop_no_content
    ],
    # APPLY preprocessing.remove_digits(only_blocks=False) TO THE CUSTOM PIPELINE AFTER CLEANING
    'FINALISED_DATA_LIST': [],
    'DATA_COLUMN': None,
    'TOKENIZE': True,
    'EXTEND_STOPWORD': False,
    'STOPWORD_LIST': '',
    'ENGLISH_WORDS': set(nltk.corpus.words.words()),
    'FINALISE': False,
    'ANALYSIS_MODE': 'Data Cleaning',
    'WORLD_MAP': True,
    'GLOBE_DATA': None,
    'GLOBE_FIG': None,
    'MATCH': False,
    'QUERY': None,
    'QUERY_SUCCESS': False,
    'QUERY_MODE': None,
    'QUERY_DATA': pd.DataFrame(),
    'MOD_MODE': 'Country Extraction',
    'FIXED_KEY': True,
    'HEIGHT': 400
}

dtm = {
    'DTM': pd.DataFrame(),
    'FILE': 'Small File(s)',
    'DATA': pd.DataFrame(),
    'DATA_PATH': None,
    'ANALYSIS': False,
    'VERBOSE_DTM': False,
    'VERBOSITY_DTM': False,
    'VERBOSE_ANALYSIS': False,
    'SAVE': False,
    'OVERRIDE_FORMAT': None,
    'MODE': 'CSV',
    'DTM_copy': pd.DataFrame(),
    'N': 100,
    'CSP': None,
    'ADVANCED_ANALYSIS': False,
    'FINALISED_DATA_LIST': [],
    'DATA_COLUMN': None,
    'TOP_N_WORD_FIG': None
}

toolkit = {
    'DATA': pd.DataFrame(),
    'FILE': 'Small File(s)',
    'MODE': 'CSV',
    'DATA_PATH': None,
    'CSP': None,
    'SAVE': False,
    'OVERRIDE_FORMAT': None,
    'VERBOSE': False,
    'VERBOSITY': 20,
    'APP_MODE': 'Wordcloud',
    'BACKEND_ANALYSER': 'VADER',
    'MAX_WORDS': 200,
    'CONTOUR_WIDTH': 3,
    'HEIGHT': 400,
    'WIDTH': 800,
    'SENT_LEN': 3,
    'NUM_TOPICS': 10,
    'TOPIC_FRAME': None,
    'LDA_VIS': None,
    'LDA_MODEL': None,
    'KW': None,
    'TFIDF_MODEL': None,
    'TFIDF_VECTORISED': None,
    'NMF_MODEL': None,
    'LSI_MODEL': None,
    'LSI_DATA': None,
    'MAR_FIG': None,
    'WORD_FIG': None,
    'LDA_VIS_STR': None,
    'LDA_DATA': None,
    'MODEL': None,
    'ADVANCED_ANALYSIS': False,
    'NLP_MODEL': 'en_core_web_sm',
    'DATA_COLUMN': None,
    'NLP': None,
    'ONE_DATAPOINT': False,
    'DATAPOINT_SELECTOR': 0,
    'NLP_TOPIC_MODEL': 'Latent Dirichlet Allocation',
    'MIN_DF': 2,
    'MAX_DF': 0.95,
    'MAX_ITER': 100,
    'CV': None,
    'VECTORISED': None,
    'COLOUR': None,
    'COLOUR_BCKGD': None,
    'COLOUR_TXT': None,
    'TOPIC_TEXT': [],
    'SVG': None,
    'HAC_PLOT': None,
    'HAC_PLOT1': None,
    'WORKER': 1,
    'MAX_FEATURES': 5000,
    'ALPHA': 0.1,
    'L1_RATIO': 0.5,
    'PLOT': False,
    'W_PLOT': False,
    'MIN_WORDS': 80,
    'SUM_MODE': 'Basic'
}

trainer = {
    'TRANSFORMERS_CHOICES': ('Pre Training', 'CausalLM', 'MaskedLM', 'Seq2SeqLM', 'SequenceClassification',
                             'MultipleChoice', 'NextSentencePrediction', 'TokenClassificaition', 'QuestionAnswering',
                             'TableQuestionAnswering'),
    'TRANSFORMERS_SELECTION': None,
    'MODEL_MODE': 'Training',
    'MODEL_FILE': None,
    'TRAINING_PARAMS': [],
    'API': True,
    'attack': None,
    'model_max_length': None,
    'model_num_labels': None,
    'dataset_train_split': None,
    'dataset_eval_split': None,
    'filter_train_by_labels': None,
    'filter_eval_by_labels': None,
    'num_epochs': 3,
    'num_clean_epochs': 1,
    'attack_epoch_interval': 1,
    'early_stopping_epochs': None,
    'learning_rate': 5e-5,
    'num_warmup_steps': 500,
    'weight_decay': 0.01,
    'per_device_train_batch_size': 8,
    'per_device_eval_batch_size': 32,
    'gradient_accumulation_steps': 1,
    'random_seed': 786,
    'parallel': False,
    'load_best_model_at_end': False,
    'alpha': 1.0,
    'num_train_adv_examples': -1,
    'query_budget_train': None,
    'attack_num_workers_per_device': 1,
    'output_dir': None,
    # 'output_dir': f'{os.getcwd()}/outputs/{datetime.now().strftime("%Y-%m-%d-%H-%M-%S-%f")}',
    'checkpoint_interval_steps': None,
    'checkpoint_interval_epochs': None,
    'save_last': True,
    'log_to_tb': False,
    'tb_log_dir': None,
    # 'tb_log_dir': r'./runs',
    'log_to_wandb': False,
    'wandb_project': 'textattack',
    'logging_interval_step': 1,
    'ML_MODEL': '',
    'ML_POSSIBLE_PICKS': ('albert-base-v2-CoLA', 'bert-base-uncased-CoLA', 'distilbert-base-cased-CoLA',
                          'distilbert-base-uncased-CoLA', 'roberta-base-CoLA', 'xlnet-base-cased-CoLA',
                          'albert-base-v2-RTE', 'albert-base-v2-snli', 'albert-base-v2-WNLI', 'bert-base-uncased-MNLI',
                          'bert-base-uncased-QNLI', 'bert-base-uncased-RTE', 'bert-base-uncased-snli',
                          'bert-base-uncased-WNLI', 'distilbert-base-cased-snli', 'distilbert-base-uncased-MNLI',
                          'distilbert-base-uncased-RTE', 'distilbert-base-uncased-WNLI', 'roberta-base-QNLI',
                          'roberta-base-RTE', 'roberta-base-WNLI', 'xlnet-base-cased-RTE', 'xlnet-base-cased-WNLI',
                          'albert-base-v2-QQP', 'bert-base-uncased-QQP', 'distilbert-base-uncased-QNLI',
                          'distilbert-base-cased-QQP', 'albert-base-v2-STS-B', 'bert-base-uncased-MRPC',
                          'bert-base-uncased-STS-B', 'distilbert-base-cased-MRPC', 'distilbert-base-cased-STS-B',
                          'distilbert-base-uncased-MRPC', 'roberta-base-MRPC', 'roberta-base-STS-B',
                          'xlnet-base-cased-MRPC', 'xlnet-base-cased-STS-B', 'albert-base-v2-imdb',
                          'albert-base-v2-rotten-tomatoes', 'albert-base-v2-SST-2', 'albert-base-v2-yelp-polarity',
                          'bert-base-uncased-imdb', 'bert-base-uncased-rotten-tomatoes', 'bert-base-uncased-SST-2',
                          'bert-base-uncased-yelp-polarity', 'cnn-imdb', 'cnn-mr', 'cnn-sst2', 'cnn-yelp',
                          'distilbert-base-cased-SST-2', 'distilbert-base-uncased-imdb',
                          'distilbert-base-uncased-rotten-tomatoes', 'lstm-imdb', 'lstm-mr', 'lstm-sst2', 'lstm-yelp',
                          'roberta-base-imdb', 'roberta-base-rotten-tomatoes', 'roberta-base-SST-2',
                          'xlnet-base-cased-imdb', 'xlnet-base-cased-rotten-tomatoes', 'albert-base-v2-ag-news',
                          'bert-base-uncased-ag-news', 'cnn-ag-news', 'distilbert-base-uncased-ag-news', 'lstm-ag-news',
                          'roberta-base-ag-news', 'bert-base-uncased', 'bert-large-uncased', 'bert-base-cased',
                          'bert-large-cased', 'bert-base-multilingual-uncased', 'bert-base-multilingual-cased',
                          'bert-base-chinese', 'bert-base-german-cased', 'bert-large-uncased-whole-word-masking',
                          'bert-large-cased-whole-word-masking',
                          'bert-large-uncased-whole-word-masking-finetuned-squad',
                          'bert-large-cased-whole-word-masking-finetuned-squad',
                          'bert-base-cased-finetuned-mrpc', 'bert-base-german-dbmdz-cased',
                          'bert-base-german-dbmdz-uncased', 'cl-tohoku/bert-base-japanese',
                          'cl-tohoku/bert-base-japanese-whole-word-masking', 'cl-tohoku/bert-base-japanese-char',
                          'cl-tohoku/bert-base-japanese-char-whole-word-masking', 'TurkuNLP/bert-base-finnish-cased-v1',
                          'TurkuNLP/bert-base-finnish-uncased-v1', 'wietsedv/bert-base-dutch-cased', 'openai-gpt',
                          'gpt2', 'gpt2-medium', 'gpt2-large', 'gpt2-xl', 'transfo-xl-wt103', 'xlnet-base-cased',
                          'xlnet-large-cased', 'xlm-mlm-en-2048', 'xlm-mlm-ende-1024', 'xlm-mlm-enfr-1024',
                          'xlm-mlm-enro-1024', 'xlm-mlm-xnli15-1024', 'xlm-mlm-tlm-xnli15-1024', 'xlm-clm-enfr-1024',
                          'xlm-clm-ende-1024', 'xlm-mlm-17-1280', 'xlm-mlm-100-1280', 'roberta-base', 'roberta-large',
                          'roberta-large-mnli', 'distilroberta-base', 'roberta-base-openai-detector',
                          'roberta-large-openai-detector', 'distilbert-base-uncased',
                          'distilbert-base-uncased-distilled-squad', 'distilbert-base-cased',
                          'distilbert-base-cased-distilled-squad', 'distilgpt2',
                          'distilbert-base-german-cased', 'distilbert-base-multilingual-cased', 'ctrl',
                          'camembert-base', 'albert-base-v1', 'albert-large-v1', 'albert-xlarge-v1',
                          'albert-xxlarge-v1', 'albert-base-v2', 'albert-large-v2', 'albert-xlarge-v2',
                          'albert-xxlarge-v2', 't5-small', 't5-base', 't5-large', 't5-3B', 't5-11B', 'xlm-roberta-base',
                          'xlm-roberta-large', 'flaubert/flaubert_small_cased',
                          'flaubert/flaubert_base_uncased', 'flaubert/flaubert_base_cased',
                          'flaubert/flaubert_large_cased', 'facebook/bart-large',
                          'facebook/bart-base', 'facebook/bart-large-mnli',
                          'facebook/bart-large-cnn', 'DialoGPT-small', 'DialoGPT-medium',
                          'DialoGPT-large', 'reformer-enwik8', 'reformer-crime-and-punishment',
                          'Helsinki-NLP/opus-mt-{src}-{tgt}', 'google/pegasus-{dataset}',
                          'allenai/longformer-base-4096', 'allenai/longformer-large-4096',
                          'facebook/mbart-large-cc25', 'facebook/mbart-large-en-ro',
                          'lxmert-base-uncased', 'funnel-transformer/small',
                          'funnel-transformer/small-base', 'funnel-transformer/medium',
                          'funnel-transformer/medium-base', 'funnel-transformer/intermediate',
                          'funnel-transformer/intermediate-base', 'funnel-transformer/large',
                          'funnel-transformer/large-base', 'funnel-transformer/xlarge',
                          'funnel-transformer/xlarge-base', 'microsoft/layoutlm-base-uncased',
                          'microsoft/layoutlm-large-uncased'),
    'DATASET_POSSIBLE_PICKS': ('super_glue', 'glue', 'anli', 'wino_bias', 'squad', 'imdb', 'wikitext', 'trec', 'race',
                               'adversarial_qa', 'duorc', 'squad_v2', 'winogrande', 'cosmos_qa', 'quail', 'xsum',
                               'cnn_dailymail', 'piqa', 'paws', 'hellaswag', 'ai2_arc', 'ropes', 'rotten_tomatoes',
                               'amazon_polarity', 'quoref', 'wiki_qa', 'cos_e', 'hans', 'ag_news', 'common_gen',
                               'mc_taco', 'gigaword', 'wiki_hop', 'wmt16', 'wiqa', 'qasc', 'winograd_wsc',
                               'common_voice', 'quartz', 'yelp_review_full', 'samsum', 'crows_pairs', 'openbookqa',
                               'qa_srl', 'multi_news', 'social_i_qa', 'nq_open', 'quac', 'web_questions', 'dream',
                               'kilt_tasks', 'wiki_bio', 'drop', 'trivia_qa', 'sciq', 'quarel', 'lambada', 'coqa',
                               'circa', 'mc4', 'conll2003', 'dbpedia_14', 'xnli', 'emotion', 'story_cloze',
                               'app_reviews', 'snli', 'mlqa', 'code_search_net', 'c4', 'multi_nli',
                               'amazon_reviews_multi', 'hate_speech18', 'tweet_eval', 'timit_asr', 'oscar', 'sst',
                               'hate_speech_offensive', 'wikiann', 'wikipedia', 'opus_euconst', 'math_qa', 'swag',
                               'pubmed_qa', 'scientific_papers', 'banking77', 'cbt', 'commonsense_qa', 'yelp_polarity',
                               'stsb_multi_mt', 'bookcorpus', 'squad_adversarial', 'scan', 'financial_phrasebank',
                               'craffel/openai_lambada', 'wiki_dpr', 'amazon_us_reviews', 'math_dataset', 'tab_fact',
                               'subjqa', 'OTHERS'),
    # mappings area split -> dataset: [(subsets), (dataset_columns), (split)]
    'SUBSET_MAPPINGS': {'super_glue': [('boolq', 'cb', 'copa', 'multirc', 'record', 'rte', 'wic', 'wsc', 'wsc.fixed',
                                        'axb', 'axg'), (), ('train', 'test', 'validation')],
                        'glue': [('cola', 'sst2', 'mrpc', 'qqp', 'stsb', 'mnli', 'mnli_mismatched', 'mnli_matched',
                                  'qnli', 'rte', 'wnli', 'ax'), (), ('train', 'test', 'validation')],
                        'anli': [(), (), ('train_r1', 'dev_r1', 'test_r1', 'train_r2', 'dev_r2', 'test_r2',
                                          'train_r3', 'dev_r3', 'test_r3')],
                        'wino_bias': [('type1_pro', 'type1_anti', 'type2_pro', 'type2_anti'), (),
                                      ('test', 'validation')],
                        'squad': [(), ('question', 'title', 'id', 'context', 'answers'), ('train', 'validation')],
                        'imdb': [(), (), ('train', 'test', 'unsupervised')],
                        'wikitext': [('wikitext-103-raw-v1', 'wikitext-2-raw-v1', 'wikitext-103-v1', 'wikitext-2-v1'),
                                     (), ('train', 'test', 'validation')],
                        'trec': [(), ('label-coarse', 'text', 'label-fine'), ('train', 'test')],
                        'race': [('high', 'middle', 'all'), ('example_id', 'article', 'answer', 'question', 'options'),
                                 ('train', 'test', 'validation')],
                        'adversarial_qa': [('adversarialQA', 'dbidaf', 'dbert', 'droberta'), (),
                                           ('train', 'test', 'validation')],
                        'duorc': [('SelfRC', 'ParaphraseRC'), (), ('train', 'test', 'validation')],
                        'squad_v2': [(), ('question', 'title', 'id', 'context', 'answers'), ('train', 'validation')],
                        'winogrande': [('winogrande_xs', 'winogrande_s', 'winogrande_m', 'winogrande_l',
                                        'winogrande_xl', 'winogrande_debiased'), (), ('train', 'test', 'validation')],
                        'cosmos_qa': [(), ('question', 'answer2', 'answer0', 'answer1', 'label', 'id', 'answer3',
                                           'context'), ('train', 'test', 'validation')],
                        'quail': [(), ('question', 'question_type', 'id', 'context_id', 'domain', 'context',
                                       'correct_answer_id', 'answers', 'question_id', 'metadata'),
                                  ('train', 'challenge', 'validation')],
                        'xsum': [(), (), ('train', 'test', 'validation')],
                        'cnn_dailymail': [(), (), ('train', 'test', 'validation')],
                        'piqa': [(), (), ('train', 'test', 'validation')],
                        'paws': [('labelle_final', 'labelled_swap', 'unlabelled_final'),
                                 (), ('train', 'test', 'validation')],
                        'hellaswag': [(), (), ('train', 'test', 'validation')],
                        'ai2_arc': [('ARC-Challenge', 'ARC-Easy'), (), ('train', 'test', 'validation')],
                        'ropes': [(), (), ('train', 'test', 'validation')],
                        'rotten_tomatoes': [(), (), ('train', 'test', 'validation')],
                        'amazon_polarity': [(), (), ()],
                        'quoref': [(), (), ('train', 'validation')],
                        'wiki_qa': [(), (), ()],
                        'cos_e': [('v1.0', 'v1.11'), (), ('train', 'validation')],
                        'hans': [(), (), ('train', 'validation')],
                        'ag_news': [(), (), ('train', 'test')],
                        'common_gen': [(), (), ('train', 'test', 'validation')],
                        'mc_taco': [(), (), ('test', 'validation')],
                        'gigaword': [(), (), ('train', 'test', 'validation')],
                        'wiki_hop': [('original', 'masked'), (), ('train', 'validation')],
                        'wmt16': [('cs-en', 'de-en', 'fi-en', 'ro-en', 'ru-en', 'te-en'),
                                  (), ('train', 'test', 'validation')],
                        'wiqa': [(), (), ('train', 'test', 'validation')],
                        'qasc': [(), (), ('train', 'test', 'validation')],
                        'winograd_wsc': [(), (), ()],
                        'common_voice': [(), (), ()],
                        'quartz': [(), (), ('train', 'test', 'validation')],
                        'yelp_review_full': [(), (), ()],
                        'samsum': [(), (), ('train', 'test', 'val')],
                        'crows_pairs': [(), (), ()],
                        'openbookqa': [('main', 'additional'), (), ('train', 'test', 'validation')],
                        'qa_srl': [(), (), ('train', 'test', 'validation')],
                        'multi_news': [(), (), ('train', 'test', 'validation')],
                        'social_i_qa': [(), (), ('train', 'validation')],
                        'nq_open': [(), (), ('train', 'validation')],
                        'quac': [(), (), ('train', 'validation')],
                        'web_questions': [(), (), ('train', 'test')],
                        'dream': [(), (), ('train', 'test', 'validation')],
                        'kilt_tasks': [('triviaqa_support_only', 'fever', 'aidayago2', 'wned', 'cweb', 'trex',
                                        'structured_zeroshot', 'nq', 'hotpotqa', 'eli5', 'wow'),
                                       (), ('train', 'test', 'validation')],
                        'wiki_bio': [(), (), ('train', 'test', 'validation')],
                        'drop': [(), (), ('train', 'validation')],
                        'trivia_qa': [('rc', 'rc.nocontext', 'unfiltered', 'unfiltered.nocontext'),
                                      (), ('train', 'test', 'validation')],
                        'sciq': [(), (), ('train', 'test', 'validation')],
                        'quarel': [(), (), ('train', 'test', 'validation')],
                        'lambada': [(), (), ('train', 'test', 'dev')],
                        'coqa': [(), (), ('train', 'validation')],
                        'circa': [(), (), ('train')],
                        'mc4': [('af', 'am', 'ar', 'az', 'be', 'bg', 'bg-Latn', 'bn', 'ca', 'ceb', 'co', 'cs', 'cy',
                                 'da', 'de', 'el', 'el-Latn', 'en', 'eo', 'es', 'et', 'eu', 'fa', 'fi', 'fil', 'fr',
                                 'fy', 'ga', 'gd', 'gl', 'gu', 'ha', 'haw', 'hi', 'hi-Latn', 'hmn', 'ht', 'hu', 'hy',
                                 'id', 'ig', 'is', 'it', 'iw', 'ja', 'ja-Latn', 'jv', 'ka', 'kk', 'km', 'kn', 'ko',
                                 'ku', 'ky', 'la', 'lb', 'lo', 'lt', 'lv', 'mg', 'mi', 'mk', 'ml', 'mn', 'mr', 'ms',
                                 'mt', 'my', 'ne', 'nl', 'no', 'ny', 'pa', 'pl', 'ps', 'pt', 'ro', 'ru', 'ru-Latn',
                                 'sd', 'si', 'sk', 'sl', 'sm', 'sn', 'so', 'sq', 'sr', 'st', 'su', 'sv', 'sw', 'ta',
                                 'te', 'tg', 'th', 'tr', 'uk', 'und', 'ur', 'uz', 'vi', 'xh', 'yi', 'yo', 'zh',
                                 'zh-Latn', 'zu'), (), ('train', 'test', 'validation')],

                        'conll2003': [(), (), ('train', 'test', 'validation')],
                        'dbpedia_14': [(), (), ('train', 'test')],
                        'xnli': [('all_languages', 'ar', 'bg', 'de', 'el'), (), ('train', 'test', 'validation')],
                        'emotion': [(), (), ('train', 'test', 'validation')],
                        'story_cloze': [('2016', '2018'), (), ('test', 'validation')],
                        'app_reviews': [(), (), ()],
                        'snli': [(), (), ('train', 'test', 'validation')],
                        'mlqa': [('mlqa-translate-test.ar', 'mlqa-translate-test.de', 'mlqa-translate-test.es',
                                  'mlqa-translate-test.hi', 'mlqa-translate-test.vi'), (),
                                 ('train', 'test', 'validation')],
                        'code_search_net': [('all', 'java', 'go', 'python', 'javascript', 'ruby', 'php'),
                                            (), ('train', 'test', 'validation')],
                        'c4': [('en', 'realnewslike', 'en.noclean', 'realnewslike'),
                               (), ('train', 'validation')],
                        'multi_nli': [(), (), ('train', 'validation_matched', 'validation_mismatched')],
                        'amazon_reviews_multi': [('all_languages', 'de', 'en', 'es', 'fr', 'ja', 'zh'),
                                                 (), ('train', 'test', 'validation')],
                        'hate_speech18': [(), (), ()],
                        'tweet_eval': [('emoji', 'emotion', 'hate', 'irony', 'offensive', 'sentiment',
                                        'stance_abortion', 'stance_atheism', 'stance_climate', 'stance_feminist',
                                        'stance_hillary'), (), ('train', 'test', 'validation')],
                        'timit_asr': [(), (), ('train', 'test')],
                        'oscar': [('unshuffled_original_af', 'unshuffled_original_sq', 'unshuffled_original_als',
                                   'unshuffled_original_am', 'unshuffled_original_ar', 'unshuffled_original_an',
                                   'unshuffled_original_hy', 'unshuffled_original_as', 'unshuffled_original_ast',
                                   'unshuffled_original_av', 'unshuffled_original_az', 'unshuffled_original_ba',
                                   'unshuffled_original_eu', 'unshuffled_original_bar', 'unshuffled_original_be',
                                   'unshuffled_original_bn', 'unshuffled_original_bh', 'unshuffled_original_bpy',
                                   'unshuffled_original_bs', 'unshuffled_original_br', 'unshuffled_original_bg',
                                   'unshuffled_original_my', 'unshuffled_original_ca', 'unshuffled_original_ceb',
                                   'unshuffled_original_bcl', 'unshuffled_original_km', 'unshuffled_original_ckb',
                                   'unshuffled_original_cbk', 'unshuffled_original_ce', 'unshuffled_original_zh',
                                   'unshuffled_original_cv', 'unshuffled_original_kw', 'unshuffled_original_hr',
                                   'unshuffled_original_cs', 'unshuffled_original_da', 'unshuffled_original_dv',
                                   'unshuffled_original_diq', 'unshuffled_original_nl', 'unshuffled_original_mhr',
                                   'unshuffled_original_arz', 'unshuffled_original_eml', 'unshuffled_original_en',
                                   'unshuffled_original_myv', 'unshuffled_original_eo', 'unshuffled_original_et',
                                   'unshuffled_original_fi', 'unshuffled_original_fr', 'unshuffled_original_gl',
                                   'unshuffled_original_ka', 'unshuffled_original_de', 'unshuffled_original_gom',
                                   'unshuffled_original_gn', 'unshuffled_original_gu', 'unshuffled_original_ht',
                                   'unshuffled_original_he', 'unshuffled_original_hi', 'unshuffled_original_hu',
                                   'unshuffled_original_is', 'unshuffled_original_io', 'unshuffled_original_ilo',
                                   'unshuffled_original_id', 'unshuffled_original_ia', 'unshuffled_original_ie',
                                   'unshuffled_original_ga', 'unshuffled_original_it', 'unshuffled_original_ja',
                                   'unshuffled_original_jv', 'unshuffled_original_xal', 'unshuffled_original_kn',
                                   'unshuffled_original_krc', 'unshuffled_original_kk', 'unshuffled_original_ky',
                                   'unshuffled_original_kv', 'unshuffled_original_ko', 'unshuffled_original_ku',
                                   'unshuffled_original_lo', 'unshuffled_original_la', 'unshuffled_original_lv',
                                   'unshuffled_original_lez', 'unshuffled_original_li', 'unshuffled_original_lt',
                                   'unshuffled_original_jbo', 'unshuffled_original_lmo', 'unshuffled_original_nds',
                                   'unshuffled_original_dsb', 'unshuffled_original_lb', 'unshuffled_original_mk',
                                   'unshuffled_original_mai', 'unshuffled_original_mg', 'unshuffled_original_ms',
                                   'unshuffled_original_ml', 'unshuffled_original_mt', 'unshuffled_original_mr',
                                   'unshuffled_original_mzn', 'unshuffled_original_min', 'unshuffled_original_xmf',
                                   'unshuffled_original_mwl', 'unshuffled_original_el', 'unshuffled_original_mn',
                                   'unshuffled_original_nah', 'unshuffled_original_nap', 'unshuffled_original_ne',
                                   'unshuffled_original_new', 'unshuffled_original_frr', 'unshuffled_original_lrc',
                                   'unshuffled_original_no', 'unshuffled_original_nn', 'unshuffled_original_oc',
                                   'unshuffled_original_or', 'unshuffled_original_os', 'unshuffled_original_pam',
                                   'unshuffled_original_pa', 'unshuffled_original_fa', 'unshuffled_original_pms',
                                   'unshuffled_original_pl', 'unshuffled_original_pt', 'unshuffled_original_ps',
                                   'unshuffled_original_qu', 'unshuffled_original_ro', 'unshuffled_original_rm',
                                   'unshuffled_original_bxr', 'unshuffled_original_ru', 'unshuffled_original_sa',
                                   'unshuffled_original_gd', 'unshuffled_original_sr', 'unshuffled_original_sh',
                                   'unshuffled_original_scn', 'unshuffled_original_sd', 'unshuffled_original_si',
                                   'unshuffled_original_sk', 'unshuffled_original_sl', 'unshuffled_original_so',
                                   'unshuffled_original_azb', 'unshuffled_original_es', 'unshuffled_original_su',
                                   'unshuffled_original_sw', 'unshuffled_original_sv', 'unshuffled_original_tl',
                                   'unshuffled_original_tg', 'unshuffled_original_ta', 'unshuffled_original_tt',
                                   'unshuffled_original_te', 'unshuffled_original_th', 'unshuffled_original_bo',
                                   'unshuffled_original_tr', 'unshuffled_original_tk', 'unshuffled_original_tyv',
                                   'unshuffled_original_ug', 'unshuffled_original_uk', 'unshuffled_original_hsb',
                                   'unshuffled_original_ur', 'unshuffled_original_uz', 'unshuffled_original_vec',
                                   'unshuffled_original_vi', 'unshuffled_original_vo', 'unshuffled_original_wa',
                                   'unshuffled_original_war', 'unshuffled_original_cy', 'unshuffled_original_fy',
                                   'unshuffled_original_mrj', 'unshuffled_original_pnb', 'unshuffled_original_wuu',
                                   'unshuffled_original_sah', 'unshuffled_original_yi', 'unshuffled_original_yo',
                                   'unshuffled_original_yue', 'unshuffled_deduplicated_af',
                                   'unshuffled_deduplicated_sq', 'unshuffled_deduplicated_als',
                                   'unshuffled_deduplicated_am', 'unshuffled_deduplicated_ar',
                                   'unshuffled_deduplicated_an', 'unshuffled_deduplicated_hy',
                                   'unshuffled_deduplicated_as', 'unshuffled_deduplicated_ast',
                                   'unshuffled_deduplicated_av', 'unshuffled_deduplicated_az',
                                   'unshuffled_deduplicated_ba', 'unshuffled_deduplicated_eu',
                                   'unshuffled_deduplicated_bar', 'unshuffled_deduplicated_be',
                                   'unshuffled_deduplicated_bn', 'unshuffled_deduplicated_bh',
                                   'unshuffled_deduplicated_bpy', 'unshuffled_deduplicated_bs',
                                   'unshuffled_deduplicated_br', 'unshuffled_deduplicated_bg',
                                   'unshuffled_deduplicated_my', 'unshuffled_deduplicated_ca',
                                   'unshuffled_deduplicated_ceb', 'unshuffled_deduplicated_bcl',
                                   'unshuffled_deduplicated_km', 'unshuffled_deduplicated_ckb',
                                   'unshuffled_deduplicated_cbk', 'unshuffled_deduplicated_ce',
                                   'unshuffled_deduplicated_zh', 'unshuffled_deduplicated_cv',
                                   'unshuffled_deduplicated_kw', 'unshuffled_deduplicated_hr',
                                   'unshuffled_deduplicated_cs', 'unshuffled_deduplicated_da',
                                   'unshuffled_deduplicated_dv', 'unshuffled_deduplicated_diq',
                                   'unshuffled_deduplicated_nl', 'unshuffled_deduplicated_mhr',
                                   'unshuffled_deduplicated_arz', 'unshuffled_deduplicated_eml',
                                   'unshuffled_deduplicated_en', 'unshuffled_deduplicated_myv',
                                   'unshuffled_deduplicated_eo', 'unshuffled_deduplicated_et',
                                   'unshuffled_deduplicated_fi', 'unshuffled_deduplicated_fr',
                                   'unshuffled_deduplicated_gl', 'unshuffled_deduplicated_ka',
                                   'unshuffled_deduplicated_de', 'unshuffled_deduplicated_gom',
                                   'unshuffled_deduplicated_gn', 'unshuffled_deduplicated_gu',
                                   'unshuffled_deduplicated_ht', 'unshuffled_deduplicated_he',
                                   'unshuffled_deduplicated_hi', 'unshuffled_deduplicated_hu',
                                   'unshuffled_deduplicated_is', 'unshuffled_deduplicated_io',
                                   'unshuffled_deduplicated_ilo', 'unshuffled_deduplicated_id',
                                   'unshuffled_deduplicated_ia', 'unshuffled_deduplicated_ie',
                                   'unshuffled_deduplicated_ga', 'unshuffled_deduplicated_it',
                                   'unshuffled_deduplicated_ja', 'unshuffled_deduplicated_jv',
                                   'unshuffled_deduplicated_xal', 'unshuffled_deduplicated_kn',
                                   'unshuffled_deduplicated_krc', 'unshuffled_deduplicated_kk',
                                   'unshuffled_deduplicated_ky', 'unshuffled_deduplicated_kv',
                                   'unshuffled_deduplicated_ko', 'unshuffled_deduplicated_ku',
                                   'unshuffled_deduplicated_lo', 'unshuffled_deduplicated_la',
                                   'unshuffled_deduplicated_lv', 'unshuffled_deduplicated_lez',
                                   'unshuffled_deduplicated_li', 'unshuffled_deduplicated_lt',
                                   'unshuffled_deduplicated_jbo', 'unshuffled_deduplicated_lmo',
                                   'unshuffled_deduplicated_nds', 'unshuffled_deduplicated_dsb',
                                   'unshuffled_deduplicated_lb', 'unshuffled_deduplicated_mk',
                                   'unshuffled_deduplicated_mai', 'unshuffled_deduplicated_mg',
                                   'unshuffled_deduplicated_ms', 'unshuffled_deduplicated_ml',
                                   'unshuffled_deduplicated_mt', 'unshuffled_deduplicated_mr',
                                   'unshuffled_deduplicated_mzn', 'unshuffled_deduplicated_min',
                                   'unshuffled_deduplicated_xmf', 'unshuffled_deduplicated_mwl',
                                   'unshuffled_deduplicated_el', 'unshuffled_deduplicated_mn',
                                   'unshuffled_deduplicated_nah', 'unshuffled_deduplicated_nap',
                                   'unshuffled_deduplicated_ne', 'unshuffled_deduplicated_new',
                                   'unshuffled_deduplicated_frr', 'unshuffled_deduplicated_lrc',
                                   'unshuffled_deduplicated_no', 'unshuffled_deduplicated_nn',
                                   'unshuffled_deduplicated_oc', 'unshuffled_deduplicated_or',
                                   'unshuffled_deduplicated_os', 'unshuffled_deduplicated_pam',
                                   'unshuffled_deduplicated_pa', 'unshuffled_deduplicated_fa',
                                   'unshuffled_deduplicated_pms', 'unshuffled_deduplicated_pl',
                                   'unshuffled_deduplicated_pt', 'unshuffled_deduplicated_ps',
                                   'unshuffled_deduplicated_qu', 'unshuffled_deduplicated_ro',
                                   'unshuffled_deduplicated_rm', 'unshuffled_deduplicated_bxr',
                                   'unshuffled_deduplicated_ru', 'unshuffled_deduplicated_sa',
                                   'unshuffled_deduplicated_gd', 'unshuffled_deduplicated_sr',
                                   'unshuffled_deduplicated_sh', 'unshuffled_deduplicated_scn',
                                   'unshuffled_deduplicated_sd', 'unshuffled_deduplicated_si',
                                   'unshuffled_deduplicated_sk', 'unshuffled_deduplicated_sl',
                                   'unshuffled_deduplicated_so', 'unshuffled_deduplicated_azb',
                                   'unshuffled_deduplicated_es', 'unshuffled_deduplicated_su',
                                   'unshuffled_deduplicated_sw', 'unshuffled_deduplicated_sv',
                                   'unshuffled_deduplicated_tl', 'unshuffled_deduplicated_tg',
                                   'unshuffled_deduplicated_ta', 'unshuffled_deduplicated_tt',
                                   'unshuffled_deduplicated_te', 'unshuffled_deduplicated_th',
                                   'unshuffled_deduplicated_bo', 'unshuffled_deduplicated_tr',
                                   'unshuffled_deduplicated_tk', 'unshuffled_deduplicated_tyv',
                                   'unshuffled_deduplicated_ug', 'unshuffled_deduplicated_uk',
                                   'unshuffled_deduplicated_hsb', 'unshuffled_deduplicated_ur',
                                   'unshuffled_deduplicated_uz', 'unshuffled_deduplicated_vec',
                                   'unshuffled_deduplicated_vi', 'unshuffled_deduplicated_vo',
                                   'unshuffled_deduplicated_wa', 'unshuffled_deduplicated_war',
                                   'unshuffled_deduplicated_cy', 'unshuffled_deduplicated_fy',
                                   'unshuffled_deduplicated_mrj', 'unshuffled_deduplicated_pnb',
                                   'unshuffled_deduplicated_wuu', 'unshuffled_deduplicated_sah',
                                   'unshuffled_deduplicated_yi', 'unshuffled_deduplicated_yo',
                                   'unshuffled_deduplicated_yue'), (), ('train', 'test', 'validation')],
                        'sst': [('default', 'dictionary' 'ptb'), (), ('train', 'test', 'validation')],
                        'hate_speech_offensive': [(), (), ('train')],
                        'wikiann': [('ace', 'af', 'als', 'am', 'an', 'ang', 'ar', 'arc', 'arz', 'as', 'ast', 'ay',
                                     'az', 'ba', 'bar', 'bat-smg', 'be', 'be-x-old', 'bg', 'bh', 'bn', 'bo', 'br',
                                     'bs', 'ca', 'cbk-zam', 'cdo', 'ce', 'ceb', 'ckb', 'co', 'crh', 'cs', 'csb', 'cv',
                                     'cy', 'da', 'de', 'diq', 'dv', 'el', 'eml', 'en', 'eo', 'es', 'et', 'eu', 'ext',
                                     'fa', 'fi', 'fiu-vro', 'fo', 'fr', 'frr', 'fur', 'fy', 'ga', 'gan', 'gd', 'gl',
                                     'gn', 'gu', 'hak', 'he', 'hi', 'hr', 'hsb', 'hu', 'hy', 'ia', 'id', 'ig', 'ilo',
                                     'io', 'is', 'it', 'ja', 'jbo', 'jv', 'ka', 'kk', 'km', 'kn', 'ko', 'ksh', 'ku',
                                     'ky', 'la', 'lb', 'li', 'lij', 'lmo', 'ln', 'lt', 'lv', 'map-bms', 'mg', 'mhr',
                                     'mi', 'min', 'mk', 'ml', 'mn', 'mr', 'ms', 'mt', 'mwl', 'my', 'mzn', 'nap', 'nds',
                                     'ne', 'nl', 'nn', 'no', 'nov', 'oc', 'or', 'os', 'pa', 'pdc', 'pl', 'pms', 'pnb',
                                     'ps', 'pt', 'qu', 'rm', 'ro', 'ru', 'rw', 'sa', 'sah', 'scn', 'sco', 'sd', 'sh',
                                     'si', 'simple', 'sk', 'sl', 'so', 'sq', 'sr', 'su', 'sv', 'sw', 'szl', 'ta', 'te',
                                     'tg', 'th', 'tk', 'tl', 'tr', 'tt', 'ug', 'uk', 'ur', 'uz', 'vec', 'vep', 'vi',
                                     'vls', 'vo', 'wa', 'war', 'wuu', 'xmf', 'yi', 'yo', 'zea', 'zh', 'zh-classical',
                                     'zh-min-nan', 'zh-yue'), (), ('train', 'test', 'validation')],
                        'wikipedia': [('20200501.de', '20200501.en', '20200501.fr', '20200501.frr', '20200501.it'),
                                      (), ('train', 'test', 'validation')],
                        'opus_euconst': [('cs-da', 'cs-de', 'cs-el'), (), ('train', 'test', 'validation')],
                        'math_qa': [(), (), ('train', 'test', 'validation')],
                        'swag': [(), (), ('train', 'test', 'validation')],
                        'pubmed_qa': [(), (), ()],
                        'scientific_papers': [('pubmed', 'arxiv'), (), ('train', 'test', 'validation')],
                        'banking77': [(), (), ('train', 'test')],
                        'cbt': [('raw', 'V', 'P', 'CN', 'NE'), (), ('train', 'test', 'validation')],
                        'commonsense_qa': [(), (), ('train', 'test', 'validation')],
                        'yelp_polarity': [(), (), ('train', 'test')],
                        'stsb_multi_mt': [('en', 'de', 'es', 'ft', 'it', 'nl', 'pl', 'pt', 'ru', 'zh'),
                                          (), ('train', 'test', 'validation')],
                        'bookcorpus': [(), (), ('train')],
                        'squad_adversarial': [('AddSent', 'AddOneSent'), (), ()],
                        'scan': [('addprim_jump', 'addprim_turn_left', 'filler_num0', 'filler_num1', 'filler_num2'),
                                 (), ('train', 'test')],
                        'financial_phrasebank': [('sentences_50agree', 'sentences_66agree', 'sentences_75agree',
                                                  'sentences_allagree'), (), ()],
                        'craffel/openai_lambada': [(), (), ('test')],
                        'wiki_dpr': [('psgs_w100.multiset.compressed', 'psgs_w100.multiset.exact',
                                      'psgs_w100.multiset.no_index', 'psgs_w100.nq.compressed', 'psgs_w100.nq.exact'),
                                     (), ('train')],
                        'amazon_us_reviews': [('Apparel_v1_00', 'Automotive_v1_00', 'Baby_v1_00', 'Beauty_v1_00',
                                               'Books_v1_00'), (), ('train')],
                        'math_dataset': [('algebra__linear_1d', 'algebra__linear_1d_composed', 'algebra__linear_2d',
                                          'algebra__linear_2d_composed', 'algebra__polynomial_roots'),
                                         (), ('train', 'test')],
                        'tab_fact': [(), (), ()],
                        'subjqa': [('tripadvisor', 'restaurants', 'movies', 'books', 'electronics', 'grocery'),
                                   (), ('train', 'test', 'dev')],
                        'OTHERS': [(), (), ()]},
    'SUBSET': None,
    'MODEL_COL': None,
    'SPLIT_TRAIN': None,
    'SPLIT_TEST': None,
    'DATASET': '',
    'TOKENZIER': None,
    'WRAPPED_MODEL': None,
    'TRAINING_DATA': None,
    'TASK_TYPE': None,
    'ATTACK': None,
    'ATTACK_RECIPES': ('None', 'A2T (A2T: Attack for Adversarial Training Recipe)',
                       'BAE (BAE: BERT-Based Adversarial Examples)', 'BERT-Attack', 'CheckList', 'CLARE Recipe',
                       'DeepWordBug', 'Faster Alzantot Genetic Algorithm', 'Alzantot Genetic Algorithm', 'HotFlip',
                       'Improved Genetic Algorithm', 'Input Reduction', 'Kuleshov2017', 'MORPHEUS2020',
                       'Pruthi2019: Combating with Robust Word Recognition', 'Particle Swarm Optimization', 'PWWS',
                       'Seq2Sick', 'TextBugger', 'TextFooler (Is BERT Really Robust?)'),
    'ATTACK_MODEL': None,
    'PRED_FILE': None,
    'FILE': 'Small File(s)',
    'MODE': 'CSV',
    'CSP': None,
    'DATA_COLUMN': None,
    'MODEL_PATH': None,
    'PRED_FILEPATH': None,
    'PRED_DATA': [pd.DataFrame, list],
    'PATH_EXIST': False,
    'PRED_SEQ': None,
    'PREDS': []
}
